.TH "ConfigureOneFlag.crypto" 3 "Wed Mar 7 2018" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.crypto \- Cryptography class providing for the decryption of encrypted strings\&. Key passed in is the base64 ENCODED version for extra obfuscation\&. Using defaults to maintain FIPS-197 AES compliance/interoperability: Key size - 256 bits, Block size - 128 bits  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBDecryptCS\fP (string cipherText, string sKey)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "byte [] \fBEncrypt\fP (byte[] buffer, byte[] vector)"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static byte [] \fBDecrypt\fP (byte[] buffer, byte[] vector)"
.br
.ti -1c
.RI "static byte [] \fBTransform\fP (byte[] buffer, ICryptoTransform transform)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static Random \fBrandom\fP"
.br
.ti -1c
.RI "static byte [] \fBkey\fP"
.br
.ti -1c
.RI "static RijndaelManaged \fBrm\fP"
.br
.ti -1c
.RI "static UTF8Encoding \fBencoder\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Cryptography class providing for the decryption of encrypted strings\&. Key passed in is the base64 ENCODED version for extra obfuscation\&. Using defaults to maintain FIPS-197 AES compliance/interoperability: Key size - 256 bits, Block size - 128 bits 


.PP
Definition at line 13 of file crypto\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static byte [] ConfigureOneFlag\&.crypto\&.Decrypt (byte [] buffer, byte [] vector)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 44 of file crypto\&.cs\&.
.SS "static string ConfigureOneFlag\&.crypto\&.DecryptCS (string cipherText, string sKey)\fC [static]\fP"

.PP
Definition at line 19 of file crypto\&.cs\&.
.SS "byte [] ConfigureOneFlag\&.crypto\&.Encrypt (byte [] buffer, byte [] vector)\fC [private]\fP"

.PP
Definition at line 38 of file crypto\&.cs\&.
.SS "static byte [] ConfigureOneFlag\&.crypto\&.Transform (byte [] buffer, ICryptoTransform transform)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 50 of file crypto\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "UTF8Encoding ConfigureOneFlag\&.crypto\&.encoder\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 18 of file crypto\&.cs\&.
.SS "byte [] ConfigureOneFlag\&.crypto\&.key\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 16 of file crypto\&.cs\&.
.SS "Random ConfigureOneFlag\&.crypto\&.random\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 15 of file crypto\&.cs\&.
.SS "RijndaelManaged ConfigureOneFlag\&.crypto\&.rm\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 17 of file crypto\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
