.TH "C:/Users/hinesj/Documents/Visual Studio 2015/Projects/Triggers/Triggers/Properties/AssemblyInfo.cs" 3 "Tue Aug 29 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/hinesj/Documents/Visual Studio 2015/Projects/Triggers/Triggers/Properties/AssemblyInfo.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
