.TH "C:/Users/hinesj/Documents/Visual Studio 2015/Projects/Triggers/Triggers/C1Dictionaries.cs" 3 "Tue Oct 17 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/hinesj/Documents/Visual Studio 2015/Projects/Triggers/Triggers/C1Dictionaries.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigureOneFlag\&.C1Dictionaries\fP"
.br
.RI "Management of dictionaries used for C1 data mapping/processing "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBConfigureOneFlag\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
