.TH "C:/Users/hinesj/Documents/Visual Studio 2015/Projects/Triggers/Triggers/C1WebService.cs" 3 "Wed Sep 13 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/hinesj/Documents/Visual Studio 2015/Projects/Triggers/Triggers/C1WebService.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigureOneFlag\&.C1WebService\fP"
.br
.RI "Processing for calls to ConfigureOne web service and return for further handling "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBConfigureOneFlag\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
