.TH "C:/Users/hinesj/Documents/Visual Studio 2015/Projects/Triggers/Triggers/Class1.cs" 3 "Tue Jan 9 2018" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/hinesj/Documents/Visual Studio 2015/Projects/Triggers/Triggers/Class1.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigureOneFlag\&.Triggers\fP"
.br
.RI "Primary entrypoint called from C1ORDER trigger for accessing C1 web service and returning/mapping data to SQL where appropriate "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBConfigureOneFlag\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
