.TH "ConfigureOneFlag.zCfgParmVal" 3 "Wed Jun 21 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.zCfgParmVal \- Accessor class for the cfg parmValue object (C1 Inputs)  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCO_Num\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBCO_Line\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCValue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCType\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCLabel\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBPriorityLevel\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "string \fBorder_num\fP"
.br
.ti -1c
.RI "int \fBorder_line_num\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBval\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBlabel\fP"
.br
.ti -1c
.RI "int \fBpriority_level\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Accessor class for the cfg parmValue object (C1 Inputs) 


.PP
Definition at line 12 of file zCfgParmVal\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string ConfigureOneFlag\&.zCfgParmVal\&.label\fC [private]\fP"

.PP
Definition at line 19 of file zCfgParmVal\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgParmVal\&.name\fC [private]\fP"

.PP
Definition at line 16 of file zCfgParmVal\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgParmVal\&.order_line_num\fC [private]\fP"

.PP
Definition at line 15 of file zCfgParmVal\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgParmVal\&.order_num\fC [private]\fP"

.PP
Definition at line 14 of file zCfgParmVal\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgParmVal\&.priority_level\fC [private]\fP"

.PP
Definition at line 20 of file zCfgParmVal\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgParmVal\&.type\fC [private]\fP"

.PP
Definition at line 18 of file zCfgParmVal\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgParmVal\&.val\fC [private]\fP"

.PP
Definition at line 17 of file zCfgParmVal\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string ConfigureOneFlag\&.zCfgParmVal\&.CLabel\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 47 of file zCfgParmVal\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgParmVal\&.CName\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 32 of file zCfgParmVal\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgParmVal\&.CO_Line\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 27 of file zCfgParmVal\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgParmVal\&.CO_Num\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 22 of file zCfgParmVal\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgParmVal\&.CType\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 42 of file zCfgParmVal\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgParmVal\&.CValue\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 37 of file zCfgParmVal\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgParmVal\&.PriorityLevel\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 52 of file zCfgParmVal\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
