.TH "ConfigureOneFlag.NetworkShare.NETRESOURCE" 3 "Mon Jun 5 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.NetworkShare.NETRESOURCE
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdwScope\fP = 0"
.br
.ti -1c
.RI "int \fBdwType\fP = 0"
.br
.ti -1c
.RI "int \fBdwDisplayType\fP = 0"
.br
.ti -1c
.RI "int \fBdwUsage\fP = 0"
.br
.ti -1c
.RI "string \fBlpLocalName\fP = ''"
.br
.ti -1c
.RI "string \fBlpRemoteName\fP = ''"
.br
.ti -1c
.RI "string \fBlpComment\fP = ''"
.br
.ti -1c
.RI "string \fBlpProvider\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file NetworkShare\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int ConfigureOneFlag\&.NetworkShare\&.NETRESOURCE\&.dwDisplayType = 0"

.PP
Definition at line 69 of file NetworkShare\&.cs\&.
.SS "int ConfigureOneFlag\&.NetworkShare\&.NETRESOURCE\&.dwScope = 0"

.PP
Definition at line 67 of file NetworkShare\&.cs\&.
.SS "int ConfigureOneFlag\&.NetworkShare\&.NETRESOURCE\&.dwType = 0"

.PP
Definition at line 68 of file NetworkShare\&.cs\&.
.SS "int ConfigureOneFlag\&.NetworkShare\&.NETRESOURCE\&.dwUsage = 0"

.PP
Definition at line 70 of file NetworkShare\&.cs\&.
.SS "string ConfigureOneFlag\&.NetworkShare\&.NETRESOURCE\&.lpComment = ''"

.PP
Definition at line 73 of file NetworkShare\&.cs\&.
.SS "string ConfigureOneFlag\&.NetworkShare\&.NETRESOURCE\&.lpLocalName = ''"

.PP
Definition at line 71 of file NetworkShare\&.cs\&.
.SS "string ConfigureOneFlag\&.NetworkShare\&.NETRESOURCE\&.lpProvider = ''"

.PP
Definition at line 74 of file NetworkShare\&.cs\&.
.SS "string ConfigureOneFlag\&.NetworkShare\&.NETRESOURCE\&.lpRemoteName = ''"

.PP
Definition at line 72 of file NetworkShare\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
