.TH "ConfigureOneFlag.RetrieveDrawings" 3 "Mon Oct 30 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.RetrieveDrawings
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCopyDrawings\fP (XmlDocument xmlResult, string url)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fBresult\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file RetrieveDrawings\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ConfigureOneFlag\&.RetrieveDrawings\&.CopyDrawings (XmlDocument xmlResult, string url)\fC [static]\fP"

.PP
Definition at line 15 of file RetrieveDrawings\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string ConfigureOneFlag\&.RetrieveDrawings\&.result\fC [static]\fP"

.PP
Definition at line 14 of file RetrieveDrawings\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
