.TH "ConfigureOneFlag.C1WebService" 3 "Wed Aug 23 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.C1WebService \- Processing for calls to ConfigureOne web service and return for further handling  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCallConfigureOne\fP (string key, string payload, string url)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fBSPPUBOrderNumber\fP"
.br
.ti -1c
.RI "static string \fBpubPayload\fP"
.br
.ti -1c
.RI "static string \fBpubURL\fP"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fBOutputXMLToFile\fP (string XML)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Processing for calls to ConfigureOne web service and return for further handling 


.PP
Definition at line 12 of file C1WebService\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ConfigureOneFlag\&.C1WebService\&.CallConfigureOne (string key, string payload, string url)\fC [static]\fP"

.PP
Definition at line 17 of file C1WebService\&.cs\&.
.SS "static void ConfigureOneFlag\&.C1WebService\&.OutputXMLToFile (string XML)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 261 of file C1WebService\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string ConfigureOneFlag\&.C1WebService\&.pubPayload\fC [static]\fP"

.PP
Definition at line 15 of file C1WebService\&.cs\&.
.SS "string ConfigureOneFlag\&.C1WebService\&.pubURL\fC [static]\fP"

.PP
Definition at line 16 of file C1WebService\&.cs\&.
.SS "string ConfigureOneFlag\&.C1WebService\&.SPPUBOrderNumber\fC [static]\fP"

.PP
Definition at line 14 of file C1WebService\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
