.TH "ConfigureOneFlag.StagingUtilities" 3 "Fri Oct 6 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.StagingUtilities \- Utilities used for staging of data from C1 to SQL databases  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMapXMLToSQL\fP (XmlDocument xmldoc)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fBglobalOrderNum\fP"
.br
.ti -1c
.RI "static int \fBglobalOrderLineNum\fP"
.br
.ti -1c
.RI "static string \fBdbSite\fP = ''"
.br
.ti -1c
.RI "static bool \fBfoundSite\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Utilities used for staging of data from C1 to SQL databases 


.PP
Definition at line 9 of file StagingUtilities\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ConfigureOneFlag\&.StagingUtilities\&.MapXMLToSQL (XmlDocument xmldoc)\fC [static]\fP"

.PP
Definition at line 16 of file StagingUtilities\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string ConfigureOneFlag\&.StagingUtilities\&.dbSite = ''\fC [static]\fP"

.PP
Definition at line 13 of file StagingUtilities\&.cs\&.
.SS "bool ConfigureOneFlag\&.StagingUtilities\&.foundSite = false\fC [static]\fP"

.PP
Definition at line 14 of file StagingUtilities\&.cs\&.
.SS "int ConfigureOneFlag\&.StagingUtilities\&.globalOrderLineNum\fC [static]\fP"

.PP
Definition at line 12 of file StagingUtilities\&.cs\&.
.SS "string ConfigureOneFlag\&.StagingUtilities\&.globalOrderNum\fC [static]\fP"

.PP
Definition at line 11 of file StagingUtilities\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
