.TH "ConfigureOneFlag.C1WebService" 3 "Tue May 16 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.C1WebService \- Processing for call to ConfigureOne web service and return for further handling  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCallConfigureOne\fP (string key, string payload, string url)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Processing for call to ConfigureOne web service and return for further handling 


.PP
Definition at line 12 of file C1WebService\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ConfigureOneFlag\&.C1WebService\&.CallConfigureOne (string key, string payload, string url)\fC [static]\fP"

.PP
Definition at line 14 of file C1WebService\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
