.TH "ConfigureOneFlag.C1Dictionaries" 3 "Thu Sep 28 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.C1Dictionaries \- Management of dictionaries used for C1 data mapping/processing  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBLoadWMDictionary\fP ()"
.br
.ti -1c
.RI "static void \fBLoadDBFLengthDictionary\fP ()"
.br
.ti -1c
.RI "static int \fBDBFieldLenCO\fP (string field, ref \fBzCfgCO\fP co)"
.br
.ti -1c
.RI "static int \fBDBFieldLenCOItem\fP (string field, ref \fBzCfgCOitem\fP coitem)"
.br
.ti -1c
.RI "static int \fBDBFieldLenCfgItem\fP (string field, ref \fBzCfgItem\fP citem)"
.br
.ti -1c
.RI "static int \fBDBFieldLenParmVal\fP (string field, ref \fBzCfgParmVal\fP cfg)"
.br
.ti -1c
.RI "static int \fBDBFieldLenBOM\fP (string field, ref \fBzCfgBOM\fP bom)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Dictionary< string, string > \fBwebmethods\fP = new Dictionary<string, string>()"
.br
.ti -1c
.RI "static Dictionary< string, int > \fBfieldLengths\fP = new Dictionary<string, int>()"
.br
.ti -1c
.RI "static int \fBobjectLength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Management of dictionaries used for C1 data mapping/processing 


.PP
Definition at line 8 of file C1Dictionaries\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static int ConfigureOneFlag\&.C1Dictionaries\&.DBFieldLenBOM (string field, ref \fBzCfgBOM\fP bom)\fC [static]\fP"

.PP
Definition at line 200 of file C1Dictionaries\&.cs\&.
.SS "static int ConfigureOneFlag\&.C1Dictionaries\&.DBFieldLenCfgItem (string field, ref \fBzCfgItem\fP citem)\fC [static]\fP"

.PP
Definition at line 171 of file C1Dictionaries\&.cs\&.
.SS "static int ConfigureOneFlag\&.C1Dictionaries\&.DBFieldLenCO (string field, ref \fBzCfgCO\fP co)\fC [static]\fP"

.PP
Definition at line 109 of file C1Dictionaries\&.cs\&.
.SS "static int ConfigureOneFlag\&.C1Dictionaries\&.DBFieldLenCOItem (string field, ref \fBzCfgCOitem\fP coitem)\fC [static]\fP"

.PP
Definition at line 159 of file C1Dictionaries\&.cs\&.
.SS "static int ConfigureOneFlag\&.C1Dictionaries\&.DBFieldLenParmVal (string field, ref \fBzCfgParmVal\fP cfg)\fC [static]\fP"

.PP
Definition at line 188 of file C1Dictionaries\&.cs\&.
.SS "static void ConfigureOneFlag\&.C1Dictionaries\&.LoadDBFLengthDictionary ()\fC [static]\fP"

.PP
Definition at line 21 of file C1Dictionaries\&.cs\&.
.SS "static void ConfigureOneFlag\&.C1Dictionaries\&.LoadWMDictionary ()\fC [static]\fP"

.PP
Definition at line 13 of file C1Dictionaries\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, int> ConfigureOneFlag\&.C1Dictionaries\&.fieldLengths = new Dictionary<string, int>()\fC [static]\fP"

.PP
Definition at line 11 of file C1Dictionaries\&.cs\&.
.SS "int ConfigureOneFlag\&.C1Dictionaries\&.objectLength\fC [static]\fP"

.PP
Definition at line 12 of file C1Dictionaries\&.cs\&.
.SS "Dictionary<string, string> ConfigureOneFlag\&.C1Dictionaries\&.webmethods = new Dictionary<string, string>()\fC [static]\fP"

.PP
Definition at line 10 of file C1Dictionaries\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
