.TH "ConfigureOneFlag.Triggers" 3 "Tue Jun 6 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.Triggers \- Primary entrypoint called from C1ORDER trigger for accessing C1 web service and returning/mapping data to SQL where appropriate  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBC1Order\fP ()"
.br
.ti -1c
.RI "static void \fBC1Order\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fBwsReturn\fP"
.br
.ti -1c
.RI "static string \fBcaller\fP = ''"
.br
.ti -1c
.RI "static string \fBC1URL\fP"
.br
.ti -1c
.RI "static string \fBlogSource\fP = 'C1ORDER'"
.br
.ti -1c
.RI "static string \fBlogEvent\fP"
.br
.ti -1c
.RI "static string \fBlogName\fP = 'Application'"
.br
.ti -1c
.RI "static string \fBpubOrderNumber\fP = ''"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static Dictionary< string, string > \fBwebmethods\fP = new Dictionary<string, string>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Primary entrypoint called from C1ORDER trigger for accessing C1 web service and returning/mapping data to SQL where appropriate 


.PP
Definition at line 11 of file Class1\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ConfigureOneFlag\&.Triggers\&.C1Order ()\fC [static]\fP"

.PP
Definition at line 18 of file Class1\&.cs\&.
.SS "static void ConfigureOneFlag\&.Triggers\&.C1Order ()\fC [static]\fP"

.PP
Definition at line 19 of file trigger\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "static string ConfigureOneFlag\&.Triggers\&.C1URL\fC [static]\fP"

.PP
Definition at line 16 of file Class1\&.cs\&.
.SS "static string ConfigureOneFlag\&.Triggers\&.caller = ''\fC [static]\fP"

.PP
Definition at line 15 of file Class1\&.cs\&.
.SS "string ConfigureOneFlag\&.Triggers\&.logEvent\fC [static]\fP"

.PP
Definition at line 15 of file trigger\&.cs\&.
.SS "string ConfigureOneFlag\&.Triggers\&.logName = 'Application'\fC [static]\fP"

.PP
Definition at line 16 of file trigger\&.cs\&.
.SS "string ConfigureOneFlag\&.Triggers\&.logSource = 'C1ORDER'\fC [static]\fP"

.PP
Definition at line 14 of file trigger\&.cs\&.
.SS "string ConfigureOneFlag\&.Triggers\&.pubOrderNumber = ''\fC [static]\fP"

.PP
Definition at line 17 of file trigger\&.cs\&.
.SS "Dictionary<string, string> ConfigureOneFlag\&.Triggers\&.webmethods = new Dictionary<string, string>()\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 13 of file Class1\&.cs\&.
.SS "static string ConfigureOneFlag\&.Triggers\&.wsReturn\fC [static]\fP"

.PP
Definition at line 14 of file Class1\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
