.TH "ConfigureOneFlag.zCfgRoute" 3 "Wed Mar 7 2018" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.zCfgRoute \- Accessor class for the cfg route object (C1 routing module data)  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCO_Num\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBCO_Line\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBBOM_ID\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBOPERATION\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDescription\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "double \fBLabor_Hours\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "double \fBSetup_Hours\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "double \fBLabor_Rate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBNotes\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMachine_Name\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "double \fBRun_Time\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "string \fBorder_num\fP"
.br
.ti -1c
.RI "int \fBorder_line_num\fP"
.br
.ti -1c
.RI "string \fBbom_id\fP"
.br
.ti -1c
.RI "int \fBoper_num\fP"
.br
.ti -1c
.RI "string \fBdescription\fP"
.br
.ti -1c
.RI "double \fBlabor_hrs\fP"
.br
.ti -1c
.RI "double \fBsetup_hrs\fP"
.br
.ti -1c
.RI "double \fBlabor_rate\fP"
.br
.ti -1c
.RI "string \fBnotes\fP"
.br
.ti -1c
.RI "string \fBmach_name\fP"
.br
.ti -1c
.RI "double \fBrun_time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Accessor class for the cfg route object (C1 routing module data) 


.PP
Definition at line 11 of file zCfgRoute\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string ConfigureOneFlag\&.zCfgRoute\&.bom_id\fC [private]\fP"

.PP
Definition at line 15 of file zCfgRoute\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgRoute\&.description\fC [private]\fP"

.PP
Definition at line 17 of file zCfgRoute\&.cs\&.
.SS "double ConfigureOneFlag\&.zCfgRoute\&.labor_hrs\fC [private]\fP"

.PP
Definition at line 18 of file zCfgRoute\&.cs\&.
.SS "double ConfigureOneFlag\&.zCfgRoute\&.labor_rate\fC [private]\fP"

.PP
Definition at line 20 of file zCfgRoute\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgRoute\&.mach_name\fC [private]\fP"

.PP
Definition at line 22 of file zCfgRoute\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgRoute\&.notes\fC [private]\fP"

.PP
Definition at line 21 of file zCfgRoute\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgRoute\&.oper_num\fC [private]\fP"

.PP
Definition at line 16 of file zCfgRoute\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgRoute\&.order_line_num\fC [private]\fP"

.PP
Definition at line 14 of file zCfgRoute\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgRoute\&.order_num\fC [private]\fP"

.PP
Definition at line 13 of file zCfgRoute\&.cs\&.
.SS "double ConfigureOneFlag\&.zCfgRoute\&.run_time\fC [private]\fP"

.PP
Definition at line 23 of file zCfgRoute\&.cs\&.
.SS "double ConfigureOneFlag\&.zCfgRoute\&.setup_hrs\fC [private]\fP"

.PP
Definition at line 19 of file zCfgRoute\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string ConfigureOneFlag\&.zCfgRoute\&.BOM_ID\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 35 of file zCfgRoute\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgRoute\&.CO_Line\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 30 of file zCfgRoute\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgRoute\&.CO_Num\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 25 of file zCfgRoute\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgRoute\&.Description\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 45 of file zCfgRoute\&.cs\&.
.SS "double ConfigureOneFlag\&.zCfgRoute\&.Labor_Hours\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 50 of file zCfgRoute\&.cs\&.
.SS "double ConfigureOneFlag\&.zCfgRoute\&.Labor_Rate\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 60 of file zCfgRoute\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgRoute\&.Machine_Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 70 of file zCfgRoute\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgRoute\&.Notes\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 65 of file zCfgRoute\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgRoute\&.OPERATION\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 40 of file zCfgRoute\&.cs\&.
.SS "double ConfigureOneFlag\&.zCfgRoute\&.Run_Time\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 75 of file zCfgRoute\&.cs\&.
.SS "double ConfigureOneFlag\&.zCfgRoute\&.Setup_Hours\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 55 of file zCfgRoute\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
