.TH "ConfigureOneFlag" 3 "Wed Oct 4 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAudit\fP"
.br
.RI "Write auditing information regarding mapping and assembly behavior to event log, GR_Cfg_Audit, and send email for error notifications\&. "
.ti -1c
.RI "class \fBC1Dictionaries\fP"
.br
.RI "Management of dictionaries used for C1 data mapping/processing "
.ti -1c
.RI "class \fBC1WebService\fP"
.br
.RI "Processing for calls to ConfigureOne web service and return for further handling "
.ti -1c
.RI "class \fBcrypto\fP"
.br
.RI "Cryptography class providing for the decryption of encrypted strings\&. Key passed in is the base64 ENCODED version for extra obfuscation\&. Using defaults to maintain FIPS-197 AES compliance/interoperability: Key size - 256 bits, Block size - 128 bits "
.ti -1c
.RI "class \fBDatabaseFactory\fP"
.br
.RI "Repository for all database functions and calls on behalf of the assembly "
.ti -1c
.RI "class \fBNetworkShare\fP"
.br
.ti -1c
.RI "class \fBRetrieveDrawings\fP"
.br
.ti -1c
.RI "class \fBSendMail\fP"
.br
.RI "Send email to specified users for errors encountered during XML mapping "
.ti -1c
.RI "class \fBStagingUtilities\fP"
.br
.RI "Utilities used for staging of data from C1 to SQL databases "
.ti -1c
.RI "class \fBTriggers\fP"
.br
.RI "Primary entrypoint called from C1ORDER trigger for accessing C1 web service and returning/mapping data to SQL where appropriate "
.ti -1c
.RI "class \fBzCfgBOM\fP"
.br
.RI "Accessor class for the BOM object "
.ti -1c
.RI "class \fBzCfgCO\fP"
.br
.RI "Accessor class for CO object "
.ti -1c
.RI "class \fBzCfgCOitem\fP"
.br
.RI "Accessor class for the CO Item "
.ti -1c
.RI "class \fBzCfgItem\fP"
.br
.RI "Accessor class for the item-master object "
.ti -1c
.RI "class \fBzCfgParmVal\fP"
.br
.RI "Accessor class for the cfg parmValue object (C1 Inputs) "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
