.TH "ConfigureOneFlag.DatabaseFactory" 3 "Wed Jun 7 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.DatabaseFactory \- Repository for all database functions and calls on behalf of the assembly  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetConnectionString\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBWriteRecordBOM\fP (ref \fBzCfgBOM\fP bom)"
.br
.ti -1c
.RI "static void \fBWriteRecordCItem\fP (ref \fBzCfgItem\fP item)"
.br
.ti -1c
.RI "static void \fBWriteRecordCfg\fP (ref \fBzCfgParmVal\fP cfg)"
.br
.ti -1c
.RI "static void \fBWriteRecordCOItem\fP (ref \fBzCfgCOitem\fP coitem)"
.br
.ti -1c
.RI "static void \fBWriteRecordCO\fP (ref \fBzCfgCO\fP co)"
.br
.ti -1c
.RI "static void \fBResequenceBOM\fP (string orderNumber, int orderLine)"
.br
.ti -1c
.RI "static void \fBCfgImport\fP (string orderNumber)"
.br
.ti -1c
.RI "static void \fBCleanupOrder\fP (string orderNum)"
.br
.ti -1c
.RI "static void \fBWriteAuditRecord\fP (string auditMessageL, string orderNum, int orderLine, string auditEvent)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fBconnectionString\fP = ''"
.br
.ti -1c
.RI "static string \fBemailaddr\fP = ''"
.br
.ti -1c
.RI "static string \fBemailServer\fP = ''"
.br
.ti -1c
.RI "static string \fBemailFrom\fP = ''"
.br
.ti -1c
.RI "static string \fBsplocation\fP = ''"
.br
.ti -1c
.RI "static string \fBspuname\fP = ''"
.br
.ti -1c
.RI "static string \fBsppassword\fP = ''"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static string \fBSQLCommand\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Repository for all database functions and calls on behalf of the assembly 


.PP
Definition at line 11 of file DatabaseFactory\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ConfigureOneFlag\&.DatabaseFactory\&.CfgImport (string orderNumber)\fC [static]\fP"

.PP
Definition at line 128 of file DatabaseFactory\&.cs\&.
.SS "static void ConfigureOneFlag\&.DatabaseFactory\&.CleanupOrder (string orderNum)\fC [static]\fP"

.PP
Definition at line 143 of file DatabaseFactory\&.cs\&.
.SS "static void ConfigureOneFlag\&.DatabaseFactory\&.ResequenceBOM (string orderNumber, int orderLine)\fC [static]\fP"

.PP
Definition at line 115 of file DatabaseFactory\&.cs\&.
.SS "void ConfigureOneFlag\&.DatabaseFactory\&.SetConnectionString ()"

.PP
Definition at line 21 of file DatabaseFactory\&.cs\&.
.SS "static void ConfigureOneFlag\&.DatabaseFactory\&.WriteAuditRecord (string auditMessageL, string orderNum, int orderLine, string auditEvent)\fC [static]\fP"

.PP
Definition at line 181 of file DatabaseFactory\&.cs\&.
.SS "static void ConfigureOneFlag\&.DatabaseFactory\&.WriteRecordBOM (ref \fBzCfgBOM\fP bom)\fC [static]\fP"

.PP
Definition at line 62 of file DatabaseFactory\&.cs\&.
.SS "static void ConfigureOneFlag\&.DatabaseFactory\&.WriteRecordCfg (ref \fBzCfgParmVal\fP cfg)\fC [static]\fP"

.PP
Definition at line 82 of file DatabaseFactory\&.cs\&.
.SS "static void ConfigureOneFlag\&.DatabaseFactory\&.WriteRecordCItem (ref \fBzCfgItem\fP item)\fC [static]\fP"

.PP
Definition at line 72 of file DatabaseFactory\&.cs\&.
.SS "static void ConfigureOneFlag\&.DatabaseFactory\&.WriteRecordCO (ref \fBzCfgCO\fP co)\fC [static]\fP"

.PP
Definition at line 105 of file DatabaseFactory\&.cs\&.
.SS "static void ConfigureOneFlag\&.DatabaseFactory\&.WriteRecordCOItem (ref \fBzCfgCOitem\fP coitem)\fC [static]\fP"

.PP
Definition at line 95 of file DatabaseFactory\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string ConfigureOneFlag\&.DatabaseFactory\&.connectionString = ''\fC [static]\fP"

.PP
Definition at line 14 of file DatabaseFactory\&.cs\&.
.SS "string ConfigureOneFlag\&.DatabaseFactory\&.emailaddr = ''\fC [static]\fP"

.PP
Definition at line 15 of file DatabaseFactory\&.cs\&.
.SS "string ConfigureOneFlag\&.DatabaseFactory\&.emailFrom = ''\fC [static]\fP"

.PP
Definition at line 17 of file DatabaseFactory\&.cs\&.
.SS "string ConfigureOneFlag\&.DatabaseFactory\&.emailServer = ''\fC [static]\fP"

.PP
Definition at line 16 of file DatabaseFactory\&.cs\&.
.SS "string ConfigureOneFlag\&.DatabaseFactory\&.splocation = ''\fC [static]\fP"

.PP
Definition at line 18 of file DatabaseFactory\&.cs\&.
.SS "string ConfigureOneFlag\&.DatabaseFactory\&.sppassword = ''\fC [static]\fP"

.PP
Definition at line 20 of file DatabaseFactory\&.cs\&.
.SS "string ConfigureOneFlag\&.DatabaseFactory\&.spuname = ''\fC [static]\fP"

.PP
Definition at line 19 of file DatabaseFactory\&.cs\&.
.SS "string ConfigureOneFlag\&.DatabaseFactory\&.SQLCommand\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 13 of file DatabaseFactory\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
