.TH "ConfigureOneFlag.SendMail" 3 "Tue Aug 1 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.SendMail \- Send email to specified users for errors encountered during XML mapping  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMailMessage\fP (string messageBody, string messageSubject)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Send email to specified users for errors encountered during XML mapping 


.PP
Definition at line 8 of file SendMail\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ConfigureOneFlag\&.SendMail\&.MailMessage (string messageBody, string messageSubject)\fC [static]\fP"

.PP
Definition at line 10 of file SendMail\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
