.TH "ConfigureOneFlag.C1WebService" 3 "Thu Nov 9 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.C1WebService \- Processing for calls to ConfigureOne web service and return for further handling  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCallConfigureOne\fP (string key, string payload, string url)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fBSPPUBOrderNumber\fP"
.br
.ti -1c
.RI "static string \fBpubPayload\fP"
.br
.ti -1c
.RI "static string \fBpubURL\fP"
.br
.ti -1c
.RI "static string \fBSPOrderNumber\fP"
.br
.ti -1c
.RI "static XmlDocument \fBxmlResultParm\fP"
.br
.ti -1c
.RI "static string \fBurlParm\fP"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fBOutputXMLToFile\fP (string XML)"
.br
.ti -1c
.RI "static void \fBStartCopy\fP ()"
.br
.ti -1c
.RI "static void \fBMapToSyteline\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Processing for calls to ConfigureOne web service and return for further handling 


.PP
Definition at line 13 of file C1WebService\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ConfigureOneFlag\&.C1WebService\&.CallConfigureOne (string key, string payload, string url)\fC [static]\fP"

.PP
Definition at line 21 of file C1WebService\&.cs\&.
.SS "static void ConfigureOneFlag\&.C1WebService\&.MapToSyteline ()\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 252 of file C1WebService\&.cs\&.
.SS "static void ConfigureOneFlag\&.C1WebService\&.OutputXMLToFile (string XML)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 220 of file C1WebService\&.cs\&.
.SS "static void ConfigureOneFlag\&.C1WebService\&.StartCopy ()\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 239 of file C1WebService\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string ConfigureOneFlag\&.C1WebService\&.pubPayload\fC [static]\fP"

.PP
Definition at line 16 of file C1WebService\&.cs\&.
.SS "string ConfigureOneFlag\&.C1WebService\&.pubURL\fC [static]\fP"

.PP
Definition at line 17 of file C1WebService\&.cs\&.
.SS "string ConfigureOneFlag\&.C1WebService\&.SPOrderNumber\fC [static]\fP"

.PP
Definition at line 18 of file C1WebService\&.cs\&.
.SS "string ConfigureOneFlag\&.C1WebService\&.SPPUBOrderNumber\fC [static]\fP"

.PP
Definition at line 15 of file C1WebService\&.cs\&.
.SS "string ConfigureOneFlag\&.C1WebService\&.urlParm\fC [static]\fP"

.PP
Definition at line 20 of file C1WebService\&.cs\&.
.SS "XmlDocument ConfigureOneFlag\&.C1WebService\&.xmlResultParm\fC [static]\fP"

.PP
Definition at line 19 of file C1WebService\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
