.TH "ConfigureOneFlag.zCfgCOitem" 3 "Wed Mar 29 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.zCfgCOitem \- Accessor class for the CO Item  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCO_Num\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBCO_Line\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSerial\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBItem\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSmartpart\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDesc\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBUnitPrice\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBUnitCost\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBDiscount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBQTY\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBPriorityLevel\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "string \fBorder_num\fP"
.br
.ti -1c
.RI "int \fBorder_line_num\fP"
.br
.ti -1c
.RI "string \fBser_num\fP"
.br
.ti -1c
.RI "string \fBitem_num\fP"
.br
.ti -1c
.RI "string \fBsmartpart_num\fP"
.br
.ti -1c
.RI "string \fBdescription\fP"
.br
.ti -1c
.RI "decimal \fBunit_price\fP"
.br
.ti -1c
.RI "decimal \fBunit_cost\fP"
.br
.ti -1c
.RI "decimal \fBdiscount_amt\fP"
.br
.ti -1c
.RI "decimal \fBquantity\fP"
.br
.ti -1c
.RI "int \fBpriority_level\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Accessor class for the CO Item 


.PP
Definition at line 12 of file zCfgCOItem\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string ConfigureOneFlag\&.zCfgCOitem\&.description\fC [private]\fP"

.PP
Definition at line 19 of file zCfgCOItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgCOitem\&.discount_amt\fC [private]\fP"

.PP
Definition at line 22 of file zCfgCOItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgCOitem\&.item_num\fC [private]\fP"

.PP
Definition at line 17 of file zCfgCOItem\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgCOitem\&.order_line_num\fC [private]\fP"

.PP
Definition at line 15 of file zCfgCOItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgCOitem\&.order_num\fC [private]\fP"

.PP
Definition at line 14 of file zCfgCOItem\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgCOitem\&.priority_level\fC [private]\fP"

.PP
Definition at line 24 of file zCfgCOItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgCOitem\&.quantity\fC [private]\fP"

.PP
Definition at line 23 of file zCfgCOItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgCOitem\&.ser_num\fC [private]\fP"

.PP
Definition at line 16 of file zCfgCOItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgCOitem\&.smartpart_num\fC [private]\fP"

.PP
Definition at line 18 of file zCfgCOItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgCOitem\&.unit_cost\fC [private]\fP"

.PP
Definition at line 21 of file zCfgCOItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgCOitem\&.unit_price\fC [private]\fP"

.PP
Definition at line 20 of file zCfgCOItem\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int ConfigureOneFlag\&.zCfgCOitem\&.CO_Line\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 31 of file zCfgCOItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgCOitem\&.CO_Num\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 26 of file zCfgCOItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgCOitem\&.Desc\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 51 of file zCfgCOItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgCOitem\&.Discount\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 66 of file zCfgCOItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgCOitem\&.Item\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 41 of file zCfgCOItem\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgCOitem\&.PriorityLevel\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 76 of file zCfgCOItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgCOitem\&.QTY\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 71 of file zCfgCOItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgCOitem\&.Serial\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 36 of file zCfgCOItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgCOitem\&.Smartpart\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 46 of file zCfgCOItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgCOitem\&.UnitCost\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 61 of file zCfgCOItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgCOitem\&.UnitPrice\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 56 of file zCfgCOItem\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
