.TH "ConfigureOneFlag.zCfgItem" 3 "Thu Jan 25 2018" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.zCfgItem \- Accessor class for the item-master object  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCO_Num\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBCO_Line\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBSequence\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSmartpart\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBItem\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDesc\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBItemCost\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBItemPrice\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBItemSellPrice\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBItemWeight\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBUnitOfMeasure\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBPriorityLevel\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR1\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR2\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR3\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR4\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR5\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR6\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR7\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR8\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR9\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR10\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR11\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR12\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR13\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR14\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR15\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR16\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR17\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR18\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR19\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR20\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR21\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR22\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR23\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR24\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR25\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR26\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR27\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR28\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR29\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR30\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR31\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR32\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR333\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR34\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR35\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR36\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR37\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR38\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR39\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIM_VAR40\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "string \fBorder_num\fP"
.br
.ti -1c
.RI "int \fBorder_line_num\fP"
.br
.ti -1c
.RI "int \fBseq\fP"
.br
.ti -1c
.RI "string \fBsmartpart_num\fP"
.br
.ti -1c
.RI "string \fBitem_num\fP"
.br
.ti -1c
.RI "string \fBdescription\fP"
.br
.ti -1c
.RI "decimal \fBcost\fP"
.br
.ti -1c
.RI "decimal \fBprice\fP"
.br
.ti -1c
.RI "decimal \fBsell_price\fP"
.br
.ti -1c
.RI "decimal \fBweight\fP"
.br
.ti -1c
.RI "string \fBuom\fP"
.br
.ti -1c
.RI "int \fBpriority_level\fP"
.br
.ti -1c
.RI "string \fBVAR1\fP"
.br
.ti -1c
.RI "string \fBVAR2\fP"
.br
.ti -1c
.RI "string \fBVAR3\fP"
.br
.ti -1c
.RI "string \fBVAR4\fP"
.br
.ti -1c
.RI "string \fBVAR5\fP"
.br
.ti -1c
.RI "string \fBVAR6\fP"
.br
.ti -1c
.RI "string \fBVAR7\fP"
.br
.ti -1c
.RI "string \fBVAR8\fP"
.br
.ti -1c
.RI "string \fBVAR9\fP"
.br
.ti -1c
.RI "string \fBVAR10\fP"
.br
.ti -1c
.RI "string \fBVAR11\fP"
.br
.ti -1c
.RI "string \fBVAR12\fP"
.br
.ti -1c
.RI "string \fBVAR13\fP"
.br
.ti -1c
.RI "string \fBVAR14\fP"
.br
.ti -1c
.RI "string \fBVAR15\fP"
.br
.ti -1c
.RI "string \fBVAR16\fP"
.br
.ti -1c
.RI "string \fBVAR17\fP"
.br
.ti -1c
.RI "string \fBVAR18\fP"
.br
.ti -1c
.RI "string \fBVAR19\fP"
.br
.ti -1c
.RI "string \fBVAR20\fP"
.br
.ti -1c
.RI "string \fBVAR21\fP"
.br
.ti -1c
.RI "string \fBVAR22\fP"
.br
.ti -1c
.RI "string \fBVAR23\fP"
.br
.ti -1c
.RI "string \fBVAR24\fP"
.br
.ti -1c
.RI "string \fBVAR25\fP"
.br
.ti -1c
.RI "string \fBVAR26\fP"
.br
.ti -1c
.RI "string \fBVAR27\fP"
.br
.ti -1c
.RI "string \fBVAR28\fP"
.br
.ti -1c
.RI "string \fBVAR29\fP"
.br
.ti -1c
.RI "string \fBVAR30\fP"
.br
.ti -1c
.RI "string \fBVAR31\fP"
.br
.ti -1c
.RI "string \fBVAR32\fP"
.br
.ti -1c
.RI "string \fBVAR33\fP"
.br
.ti -1c
.RI "string \fBVAR34\fP"
.br
.ti -1c
.RI "string \fBVAR35\fP"
.br
.ti -1c
.RI "string \fBVAR36\fP"
.br
.ti -1c
.RI "string \fBVAR37\fP"
.br
.ti -1c
.RI "string \fBVAR38\fP"
.br
.ti -1c
.RI "string \fBVAR39\fP"
.br
.ti -1c
.RI "string \fBVAR40\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Accessor class for the item-master object 


.PP
Definition at line 12 of file zCfgItem\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "decimal ConfigureOneFlag\&.zCfgItem\&.cost\fC [private]\fP"

.PP
Definition at line 20 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.description\fC [private]\fP"

.PP
Definition at line 19 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.item_num\fC [private]\fP"

.PP
Definition at line 18 of file zCfgItem\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgItem\&.order_line_num\fC [private]\fP"

.PP
Definition at line 15 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.order_num\fC [private]\fP"

.PP
Definition at line 14 of file zCfgItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgItem\&.price\fC [private]\fP"

.PP
Definition at line 21 of file zCfgItem\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgItem\&.priority_level\fC [private]\fP"

.PP
Definition at line 25 of file zCfgItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgItem\&.sell_price\fC [private]\fP"

.PP
Definition at line 22 of file zCfgItem\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgItem\&.seq\fC [private]\fP"

.PP
Definition at line 16 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.smartpart_num\fC [private]\fP"

.PP
Definition at line 17 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.uom\fC [private]\fP"

.PP
Definition at line 24 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR1\fC [private]\fP"

.PP
Definition at line 26 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR10\fC [private]\fP"

.PP
Definition at line 35 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR11\fC [private]\fP"

.PP
Definition at line 36 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR12\fC [private]\fP"

.PP
Definition at line 37 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR13\fC [private]\fP"

.PP
Definition at line 38 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR14\fC [private]\fP"

.PP
Definition at line 39 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR15\fC [private]\fP"

.PP
Definition at line 40 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR16\fC [private]\fP"

.PP
Definition at line 41 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR17\fC [private]\fP"

.PP
Definition at line 42 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR18\fC [private]\fP"

.PP
Definition at line 43 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR19\fC [private]\fP"

.PP
Definition at line 44 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR2\fC [private]\fP"

.PP
Definition at line 27 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR20\fC [private]\fP"

.PP
Definition at line 45 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR21\fC [private]\fP"

.PP
Definition at line 46 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR22\fC [private]\fP"

.PP
Definition at line 47 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR23\fC [private]\fP"

.PP
Definition at line 48 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR24\fC [private]\fP"

.PP
Definition at line 49 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR25\fC [private]\fP"

.PP
Definition at line 50 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR26\fC [private]\fP"

.PP
Definition at line 51 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR27\fC [private]\fP"

.PP
Definition at line 52 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR28\fC [private]\fP"

.PP
Definition at line 53 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR29\fC [private]\fP"

.PP
Definition at line 54 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR3\fC [private]\fP"

.PP
Definition at line 28 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR30\fC [private]\fP"

.PP
Definition at line 55 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR31\fC [private]\fP"

.PP
Definition at line 56 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR32\fC [private]\fP"

.PP
Definition at line 57 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR33\fC [private]\fP"

.PP
Definition at line 58 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR34\fC [private]\fP"

.PP
Definition at line 59 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR35\fC [private]\fP"

.PP
Definition at line 60 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR36\fC [private]\fP"

.PP
Definition at line 61 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR37\fC [private]\fP"

.PP
Definition at line 62 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR38\fC [private]\fP"

.PP
Definition at line 63 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR39\fC [private]\fP"

.PP
Definition at line 64 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR4\fC [private]\fP"

.PP
Definition at line 29 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR40\fC [private]\fP"

.PP
Definition at line 65 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR5\fC [private]\fP"

.PP
Definition at line 30 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR6\fC [private]\fP"

.PP
Definition at line 31 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR7\fC [private]\fP"

.PP
Definition at line 32 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR8\fC [private]\fP"

.PP
Definition at line 33 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.VAR9\fC [private]\fP"

.PP
Definition at line 34 of file zCfgItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgItem\&.weight\fC [private]\fP"

.PP
Definition at line 23 of file zCfgItem\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int ConfigureOneFlag\&.zCfgItem\&.CO_Line\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 72 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.CO_Num\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 67 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.Desc\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 92 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR1\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 127 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR10\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 172 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR11\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 177 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR12\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 182 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR13\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 187 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR14\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 192 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR15\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 197 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR16\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 202 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR17\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 207 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR18\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 212 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR19\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 217 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR2\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 132 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR20\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 222 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR21\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 227 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR22\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 232 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR23\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 237 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR24\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 242 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR25\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 247 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR26\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 252 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR27\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 257 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR28\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 262 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR29\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 267 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR3\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 137 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR30\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 272 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR31\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 277 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR32\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 282 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR333\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 287 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR34\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 292 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR35\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 297 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR36\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 302 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR37\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 307 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR38\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 312 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR39\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 317 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR4\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 142 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR40\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 322 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR5\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 147 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR6\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 152 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR7\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 157 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR8\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 162 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.IM_VAR9\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 167 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.Item\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 87 of file zCfgItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgItem\&.ItemCost\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 97 of file zCfgItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgItem\&.ItemPrice\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 102 of file zCfgItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgItem\&.ItemSellPrice\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 107 of file zCfgItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgItem\&.ItemWeight\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 112 of file zCfgItem\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgItem\&.PriorityLevel\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 122 of file zCfgItem\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgItem\&.Sequence\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 77 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.Smartpart\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 82 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.UnitOfMeasure\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 117 of file zCfgItem\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
