.TH "ConfigureOneFlag.NetworkShare.ErrorClass" 3 "Thu Sep 28 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.NetworkShare.ErrorClass
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBErrorClass\fP (int \fBnum\fP, string \fBmessage\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "string \fBmessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 107 of file NetworkShare\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConfigureOneFlag\&.NetworkShare\&.ErrorClass\&.ErrorClass (int num, string message)"

.PP
Definition at line 111 of file NetworkShare\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string ConfigureOneFlag\&.NetworkShare\&.ErrorClass\&.message"

.PP
Definition at line 110 of file NetworkShare\&.cs\&.
.SS "int ConfigureOneFlag\&.NetworkShare\&.ErrorClass\&.num"

.PP
Definition at line 109 of file NetworkShare\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
