.TH "ConfigureOneFlag.zCfgItem" 3 "Thu Mar 23 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureOneFlag.zCfgItem \- Accessor class for the item-master object  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCO_Num\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBCO_Line\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBSequence\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSmartpart\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBItem\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDesc\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBItemCost\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBItemPrice\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBItemSellPrice\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "decimal \fBItemWeight\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBUnitOfMeasure\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBPriorityLevel\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "string \fBorder_num\fP"
.br
.ti -1c
.RI "int \fBorder_line_num\fP"
.br
.ti -1c
.RI "int \fBseq\fP"
.br
.ti -1c
.RI "string \fBsmartpart_num\fP"
.br
.ti -1c
.RI "string \fBitem_num\fP"
.br
.ti -1c
.RI "string \fBdescription\fP"
.br
.ti -1c
.RI "decimal \fBcost\fP"
.br
.ti -1c
.RI "decimal \fBprice\fP"
.br
.ti -1c
.RI "decimal \fBsell_price\fP"
.br
.ti -1c
.RI "decimal \fBweight\fP"
.br
.ti -1c
.RI "string \fBuom\fP"
.br
.ti -1c
.RI "int \fBpriority_level\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Accessor class for the item-master object 


.PP
Definition at line 12 of file zCfgItem\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "decimal ConfigureOneFlag\&.zCfgItem\&.cost\fC [private]\fP"

.PP
Definition at line 20 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.description\fC [private]\fP"

.PP
Definition at line 19 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.item_num\fC [private]\fP"

.PP
Definition at line 18 of file zCfgItem\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgItem\&.order_line_num\fC [private]\fP"

.PP
Definition at line 15 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.order_num\fC [private]\fP"

.PP
Definition at line 14 of file zCfgItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgItem\&.price\fC [private]\fP"

.PP
Definition at line 21 of file zCfgItem\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgItem\&.priority_level\fC [private]\fP"

.PP
Definition at line 25 of file zCfgItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgItem\&.sell_price\fC [private]\fP"

.PP
Definition at line 22 of file zCfgItem\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgItem\&.seq\fC [private]\fP"

.PP
Definition at line 16 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.smartpart_num\fC [private]\fP"

.PP
Definition at line 17 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.uom\fC [private]\fP"

.PP
Definition at line 24 of file zCfgItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgItem\&.weight\fC [private]\fP"

.PP
Definition at line 23 of file zCfgItem\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int ConfigureOneFlag\&.zCfgItem\&.CO_Line\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 32 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.CO_Num\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 27 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.Desc\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 52 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.Item\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 47 of file zCfgItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgItem\&.ItemCost\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 57 of file zCfgItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgItem\&.ItemPrice\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 62 of file zCfgItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgItem\&.ItemSellPrice\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 67 of file zCfgItem\&.cs\&.
.SS "decimal ConfigureOneFlag\&.zCfgItem\&.ItemWeight\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 72 of file zCfgItem\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgItem\&.PriorityLevel\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 82 of file zCfgItem\&.cs\&.
.SS "int ConfigureOneFlag\&.zCfgItem\&.Sequence\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 37 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.Smartpart\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 42 of file zCfgItem\&.cs\&.
.SS "string ConfigureOneFlag\&.zCfgItem\&.UnitOfMeasure\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 77 of file zCfgItem\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
