.TH "C:/Users/hinesj/Documents/Visual Studio 2015/Projects/Triggers/Triggers/crypto.cs" 3 "Fri Sep 29 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/hinesj/Documents/Visual Studio 2015/Projects/Triggers/Triggers/crypto.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigureOneFlag\&.crypto\fP"
.br
.RI "Cryptography class providing for the decryption of encrypted strings\&. Key passed in is the base64 ENCODED version for extra obfuscation\&. Using defaults to maintain FIPS-197 AES compliance/interoperability: Key size - 256 bits, Block size - 128 bits "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBConfigureOneFlag\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
