.TH "crypto.cs" 3 "Fri Mar 17 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crypto.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTriggers\&.crypto\fP"
.br
.RI "Cryptography class providing for the decryption of server connection string culled from server registry "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTriggers\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
