.TH "C:/Users/hinesj/Documents/Visual Studio 2015/Projects/Triggers/Triggers/NetworkShare.cs" 3 "Wed Mar 7 2018" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/hinesj/Documents/Visual Studio 2015/Projects/Triggers/Triggers/NetworkShare.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigureOneFlag\&.NetworkShare\fP"
.br
.ti -1c
.RI "class \fBConfigureOneFlag\&.NetworkShare\&.NETRESOURCE\fP"
.br
.ti -1c
.RI "struct \fBConfigureOneFlag\&.NetworkShare\&.ErrorClass\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBConfigureOneFlag\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
