.TH "C:/Users/hinesj/Documents/Visual Studio 2015/Projects/Triggers/Triggers/SendMail.cs" 3 "Fri Nov 10 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/hinesj/Documents/Visual Studio 2015/Projects/Triggers/Triggers/SendMail.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigureOneFlag\&.SendMail\fP"
.br
.RI "Send email to specified users for errors encountered during XML mapping "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBConfigureOneFlag\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
