.TH "C:/Users/hinesj/Documents/Visual Studio 2015/Projects/Triggers/Triggers/obj/Debug/TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs" 3 "Wed Jul 26 2017" "ConfigureOne Trigger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/hinesj/Documents/Visual Studio 2015/Projects/Triggers/Triggers/obj/Debug/TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for ConfigureOne Trigger from the source code\&.
